
const OPEN_IA_SECRET_KEY = 'YOUR_KEY_HERE';
const OPEN_IA_ORGANIZATION_ID='org-DcCBYIlOD6cf96VFX2fmRzpq';

const OPEN_IA_API_CONFIGURATION= {
    organization: OPEN_IA_ORGANIZATION_ID,
    apiKey:OPEN_IA_SECRET_KEY
}

const OPEN_IA_DEFAULT_MODEL = 'gpt-3.5-turbo';
const OPEN_IA_DEFAULT_TEMPERATURE=1
const OPEN_AI_DEFAULT_MAX_TOKENS=256
const OPEN_AI_DEFAULT_STREAM=false

module.exports= {
    OPEN_IA_API_CONFIGURATION,
    OPEN_IA_DEFAULT_MODEL,
    OPEN_IA_DEFAULT_TEMPERATURE,
    OPEN_AI_DEFAULT_MAX_TOKENS,
    OPEN_AI_DEFAULT_STREAM
}